### ISSUE TITLE
Figure out why eregs.github.io isn't displaying current info

### ISSUE THREAD

**Issue by brittag** [eregs/eregs.github.io#28]
Mentioned this in Slack, but noting it here too to track this issue - recent updates to gh-pages in this repository (such as [adding this diagram](https://github.com/eregs/eregs.github.io/pull/25) and [this page](https://github.com/eregs/eregs.github.io/pull/23)) aren't showing up on https://eregs.github.io/ - and I'm not sure why not.

**Comment by cmc333333** [comment]
Looks like the branches need to be moved around (gh-pages needs to be renamed master): https://help.github.com/articles/user-organization-and-project-pages/

**Comment by cmc333333** [comment]
This is resolved now

**Comment by brittag** [comment]
Thank you!
