### ISSUE TITLE
Server-side HTTPS enforcement for eregs.github.io

### ISSUE THREAD

**Issue by konklone** [eregs/eregs.github.io#36]
GitHub now lets you enforce HTTPS for `*.github.io` domains:

https://github.com/blog/2186-https-for-github-pages

![support page](https://help.github.com/assets/images/help/pages/enforce-https-checkbox.png)

The site already works over HTTPS without errors: https://eregs.github.io So this should be a trivial fix.

**Comment by ascott1** [comment]
Done!

**Comment by konklone** [comment]
Awesome, thank you! :smiley_cat:
