### ISSUE TITLE
Promote N&C to its own sidebar item?

### ISSUE THREAD

**Issue by brittag** [eregs/eregs.github.io#43]
I was just checking in and saw there's a new page for N&C - https://eregs.github.io/features/notice-and-comment/ - yay! I'd suggest promoting it to a left sidebar item so that people will see it, since it's cool and important. :)

**Comment by brittag** [comment]
Related, I'd love to see https://eregs.github.io/guidelines/ promoted to its own left sidebar item too. :)

**Comment by cmc333333** [comment]
Thanks @brittag -- Guidelines now has it's own sidebar item. I'd like to overhaul the whole sidebar -- I'd argue it's already too large

**Comment by brittag** [comment]
Yay for Guidelines! What I really mean here is "I would love for N&C to be easy to discover from the eRegs documentation site homepage/navigation, since N&C is such a cool project" - implementation details are up to you all. :)

**Comment by nicoleslaw** [comment]
After talking with @cmc333333, I am going to leave this under features but make some small edits to update the section and highlight it under the project history.
