### ISSUE TITLE
Consider less general project namespace

### ISSUE THREAD

**Issue by patcon** [eregs/eregs.github.io#52]
Love that this exists, but just wanted to point out that a very-similarly named government tool already exists: https://ereg.elections.ca/

Is this a concern? Will one of the projects be changing its name?

**Comment by cmc333333** [comment]
Hey there @patcon. Unfortunately, `e`-things is quite popular among government agencies. Just within this space, we've got confusion with http://www.ecfr.gov/, numerous [eRulemaking](https://www.google.com/search?as_q=eRulemaking&as_sitesearch=.gov) efforts, the United Nation's [eRegulations](http://businessfacilitation.org/eregulations/), an independent collection of hunting [eRegulations](http://www.eregulations.com/)!

This project is slowly expanding to include additional types of documents, so we're thinking about rebranding, but I don't think that'll happen anytime soon.

**Comment by patcon** [comment]
Thanks for the context :) Great to know you're thinking on it!

**Comment by patcon** [comment]
oh! aaaaand just realized this wasn't a canadian project..! i heard about it through a convo that made it sound like it was
